### ISSUE TITLE
Find better way to test database

### ISSUE THREAD

**Issue by chakeresa** [chakeresa/express_sweater_weather#9]
`shell.exec('npx sequelize db:migrate')` before/after every test is slow. There has to be a better way.

**Comment by chakeresa** [comment]
Package.json:
```
  "jest": {
    "maxConcurrency": 1,
    "globalSetup": "./tests/helper/testGlobalSetup.js",
    "globalTeardown": "./tests/helper/testGlobalTeardown.js"
  }
```
tests/helper/testCleanup.js:
```
var User = require('../../models').User;

module.exports = async function cleanup() {
  await User.destroy({ where: {} })
}
```
tests/helper/testGlobalSetup.js:
```
var shell = require('shelljs');

module.exports = () => {
  shell.exec('npx sequelize db:drop');
  shell.exec('npx sequelize db:create');
  shell.exec('npx sequelize db:migrate');
}
```
tests/helper/testGlobalTeardown.js:
```
var shell = require('shelljs');

module.exports = () => {
  shell.exec('npx sequelize db:drop');
}
```
tests/requests/forecast/forecast.spec.js (for example -- do for all test files requiring the database):
```
var request = require("supertest");
var app = require('../../../app');
var User = require('../../../models').User;
var security = require('../../../util/security');
var cleanup = require('../../helper/testCleanup');

describe('api v1 forecast', () => {
  beforeEach(() => {
    cleanup()
  });
...
```

**Comment by bplantico** [comment]
@chakeresa We (@jamescape and I) were having a terrible time with `beforeAll`, `beforeEach`, `afterEach`, and `afterAll`, then came across the `globalTearDown` in Jests docs. Unfortunately simply setting that to `true` in our package.json file didn't help, but this helped TREMENDOUSLY.

Our tests even went from ~30 seconds/run to 2 seconds! You are awesome.

**Comment by chakeresa** [comment]
@bplantico Thanks for the feedback — I’m glad it helped you!

**Comment by BrennanAyers** [comment]
@chakeresa I found that to add some further usability, passing the Model into `cleanup()` as an argument allowed you to clear whatever table you need to!

**Comment by kylecornelissen** [comment]
This solves a lot of problems when running test suites concurrently. Thank you @chakeresa!
